"""The final response schema assembled by the Phase 08 response layer.

`GeneratedResponse` and `ResponseSection` are **display data**, not
instructions: every `body` (and the assembled `text`) may contain untrusted,
display-only content derived from the learner's own input or from an LLM's
prior output (hint text, bug explanations, static-analysis messages, review
findings, etc., all produced upstream in `app.schemas.agent_results`). Never
treat any of it as instructions to an agent.

The `reveals_code` invariant enforced below is the structural guarantee that
a hint-level turn can never leak full code: it must be verifiably true from
the shape of `sections` alone, never from a caller's say-so.
"""

from typing import ClassVar, Literal

from pydantic import Field, model_validator

from app.schemas.agent_results import HintLevel
from app.schemas.base import APIModel
from app.schemas.plan import AssistanceLevel

__all__ = [
    "CODE_SECTION_KINDS",
    "GeneratedResponse",
    "ResponseSection",
    "ResponseSectionKind",
]

ResponseSectionKind = Literal[
    # DSA
    "next_hint",
    "understanding",
    "constraints",
    "brute_force",
    "why_slow",
    "key_insight",
    "pseudocode",
    "code",
    "complexity",
    "common_mistakes",
    # debug
    "static_findings",
    "inferred_approach",
    "failing_case",
    "bug_explanation",
    "patch",
    "verification",
    # explain
    "structure",
    "line_by_line",
    # review
    "findings",
    "correctness",
    # shared
    "next_steps",
    "citations",
]

CODE_SECTION_KINDS: frozenset[ResponseSectionKind] = frozenset({"code", "patch"})
"""Section kinds that carry the learner's (or a patched) full solution code.

Defined here (rather than only in `app.response.format`) so this schema's
`GeneratedResponse` validator can enforce the `reveals_code` invariant without
importing from `app.response` -- `app/schemas/*` must not import
`app/graph/*` or `app/response/*`.
"""


class ResponseSection(APIModel):
    """One rendered section of the final reply.

    `body` is markdown; it may embed untrusted, display-only text lifted
    from the learner's own code/problem statement or generated by an LLM
    over that untrusted context upstream.
    """

    kind: ResponseSectionKind
    title: str = Field(min_length=1)
    body: str = Field(min_length=1)
    language: str | None = None


class GeneratedResponse(APIModel):
    """The assembled final reply for a turn, plus the sections it was built from.

    `text` is always non-empty (see the fallback ladder documented on
    `app.response.generate.generate_response`).
    """

    text: str = Field(min_length=1)
    sections: list[ResponseSection] = Field(default_factory=list["ResponseSection"])
    assistance_level: AssistanceLevel
    hint_level: HintLevel | None = None
    hint_ceiling: HintLevel | None = None
    more_help_available: bool = False
    reveals_code: bool = False
    next_steps: list[str] = Field(default_factory=list[str])
    citations: list[str] = Field(default_factory=list[str])

    #: Assistance levels at which any code may surface at all. Phase 07's
    #: `HintResult` allows `reveals_code` only at `L5_PARTIAL`/`L6_FULL`, and
    #: `MAX_HINT_LEVEL_FOR_ASSISTANCE` maps those ceilings to exactly these two
    #: levels -- so this is that same boundary, restated for the output layer.
    CODE_BEARING_LEVELS: ClassVar[frozenset[AssistanceLevel]] = frozenset({"partial", "full"})

    @model_validator(mode="after")
    def _check_reveals_code_invariant(self) -> "GeneratedResponse":
        has_code_section = any(section.kind in CODE_SECTION_KINDS for section in self.sections)
        # The flag is no longer *iff* the sections: it must also be true when a
        # hint's own body is the code. At `partial`/`full` the ladder may reach
        # L5/L6, where `HintResult.reveals_code` is true and that hint renders
        # as the `next_hint` section, so deriving the flag from section kinds
        # alone under-reported it and misled consumers gating on it (the
        # frontend picks `st.code` vs `st.markdown`). `generate_response` owns
        # that computation; what stays enforceable here is the direction that
        # actually protects the learner -- code present implies the flag, and
        # the flag implies a level permitted to carry code.
        if has_code_section and not self.reveals_code:
            raise ValueError("a code-bearing section requires reveals_code")
        if self.reveals_code and self.assistance_level not in self.CODE_BEARING_LEVELS:
            raise ValueError(
                "reveals_code may only be true at assistance_level 'partial' or 'full'"
            )
        return self
